### ISSUE TITLE
linux version

### ISSUE THREAD

**Issue by Displacer** [jrossignol/InFlightWaypoints#15]
Is there a way to build a linux version of a plugin?

**Comment by jrossignol** [comment]
My understanding is that in general all plugins (even the ones with code) should work in linux because Unity/KSP use the Mono virtual environment.  If you want to try compiling yourself, see this page on the official wiki:

[Plugins](http://wiki.kerbalspaceprogram.com/wiki/Plugins)

If you had a specific issue with In-Flight Waypoints on linux, please reopen this issue (or open a new one).
